### PR TITLE
kubernetes challenges

### PR DESCRIPTION
**Pull request by rberrelleza**
I tried to create challenges for different levels of expertise, let me know what you think?

### CODE REVIEW

**Comment by saiyam1814** [comment]
Can you add the difficulty level with below for each challenge 
```
C_create_k3s_cluter_on_raspberrypi_b
in above scenario C represents a challenge and S represents a solution, with "_B" or "_b" representing the difficulty level which is beginner in this case. Other levels include -> Intermediate - "_I" or "_i" and Expert - "_E" or "_e"
```

**Comment by rberrelleza** [comment]
updated! do you want me to provide the solutions directly on this PR?

**Comment by saiyam1814** [comment]
Yes same would do

**Comment by saiyam1814** [comment]
Looks awesome

**Pull request merged**
