### PR TITLE
gRPC primer challenge

### LINKED ISSUE #16: gRPC primer
Would something like this be relevant?
 https://github.com/harshthakur9030/grpc-primer

### PR DESCRIPTION
**Pull request by RealHarshThakur**

### CODE REVIEW

**Comment by saiyam1814** [comment]
Hello harsh is there a working screenshot of it ? 
Also I would recommend to have your name folder under Grpc as there are lot of files here that needs to be added. and if in future there are more challenges related to grpc then would become confusing. 
challenges/grpc/harsh/challenge1 -> than all your code + working screenshot

**Comment by RealHarshThakur** [comment]
@saiyam1814 just did those changes!

**Comment by saiyam1814** [comment]
lgtm

**Comment by saiyam1814** [comment]
Hi Harsh 
its coming like 
image
Can you have separate folders inside like in kubernetes you have images folder .

**Comment by RealHarshThakur** [comment]
@saiyam1814 do you want me to do the image change or is this okay? 
Also, please add the hacktoberfest accepted label :sweat_smile:

**Pull request merged**
