### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by sangam14**

### CODE REVIEW

**Comment by saiyam1814** [comment]
Where are Challenges coming in from Golang ?

**Comment by sangam14** [comment]
@saiyam1814 merge this PR ! created Dir for Golang and adding few challenges !

**Comment by saiyam1814** [comment]
Hi @sangam14 wanted to check if this is still in progress?

**Comment by sangam14** [comment]
@saiyam1814 let me add all solutions and challenges. This PR is simple added Directory as I mentioned before in comment!

**Pull request closed without merging**
